export const NotAllowedCountries = {
  'DOM': [
    'Afghanistan',
    'Albania',
    'Belarus',
    'Bosniaand Herzegovina',
    'Burundi',
    'Burma',
    'Canada',
    'China',
    'Democratic Republic of Congo',
    'Cuba',
    'Ethiopia',
    'Guinea-Bissau',
    'Guinea',
    'Iran',
    'Iraq',
    'Japan',
    'North Korea',
    'Liberia',
    'Lebanon',
    'Libya',
    'Macedonia',
    'Malaysia',
    'New Zealand',
    'Serbia',
    'Sri Lanka',
    'Sudan',
    'Somalia',
    'Syria',
    'Thailand',
    'Trinidad and Tobago',
    'Tunisia',
    'Uganda',
    'United States of America',
    'Venezuela',
    'Yemen',
    'Zimbabwe',
  ],
};
