export const data = {
  description: {
    introduction: 'Celer Network is a leading layer 2 scaling platform that enables fast, ease and secure off-chain transactions for not only payment transitions, but also generalized off-chain smart contract. Founded by four PhDs from MIT, Princeton, UC Berkeley and UIUC, the network enables everyone to quickly build, operate, and use hightly scalable decentralized applications through innovations in off-chain scaling techniques and incentive-aligned criptoeconomics mechanizm design. Celler Network is on a mission to fully unleach the power of blockchain and revolutionize how decentralized aplications are built and used.',
    keyFeatures: [
      'Already achieved 10,000X transaction latency reduction',
      'Zero off-chain smart contract transactions fees',
      'Accelerates both payment and smart contracts',
      '100X fee reduction for micro payment',
      'Horizontally scalables as more nodes joining',
      'Provably optimal off-chain payment routing algorithm',
      'The world\'s first off-chain crypto economics model to ensure safety and ligh liquidity',
      'Blockchain agnostic (already support Ethereum, DFINITY and EVM based blockchains)'
    ],
    table: [
      {
        name: 'Token Sale Start Time',
        desc: '2019/03/19 2:00 PM (UTC)',
      },
      {
        name: 'Token Sale end Time',
        desc: 'When Hard Cap is reached or at 2019/03/24 2:00 PM (UTC)',
      },
      {
        name: 'Hard Cap',
        desc: '4,000,000 USD',
      },
      {
        name: 'Total Tocen Supply',
        desc: '10,000,000,000 CERL',
      },
      {
        name: 'Initial Circulating Supply',
        desc: '20% of Total Token Supply',
      },
      {
        name: 'Public Sale Token Price',
        desc: '0.0067 USD (price in BNB will be determined on the day of the public sale)',
      },
      {
        name: 'Launchpad Allocation',
        desc: '597,014,925 CERL (6% of Total Token Supply)',
      },
      {
        name: 'Public Sale Vesting Period',
        desc: 'No vesting period/ no lockup',
      },
      {
        name: 'individual Cap',
        desc: '1,500 USD',
      },
      {
        name: 'individual Minimum Purchase Amount',
        desc: '20 USD',
      },
      {
        name: 'Private Sale Token Price',
        desc: '1 CERL = 0.015 USD',
      },
      {
        name: 'Private Sale Allocation',
        desc: '15.5% of Total Token Supply',
      },
      {
        name: 'Private Sale Vesting Period',
        desc: 'Vesting over 3 mounths',
      },
      {
        name: 'Seed Sale Token Price',
        desc: '1 CERL = 0.0065 USD',
      },
      {
        name: 'Seed Sale Allocation',
        desc: '11.5% of Total Token Supply',
      },
      {
        name: 'Seed Sale Vesting Period',
        desc: 'Vesting over 10 mounths',
      },
      {
        name: 'Token Type',
        desc: 'ERC-20',
      },
      {
        name: 'Token Distribution',
        desc: 'Within 15 days after the token sale ends',
      },
    ]
  },
  community: [
    {
      type: 'telegram',
      url: '#'
    },
    {
      type: 'twitter',
      url: '#'
    },
    {
      type: 'facebook',
      url: '#'
    },
  ],
}


export const NotAllowedCountries = [
  'Afghanistan',
  'Bosnia and Herzegovina',
  'American Samoa',
  'Anguilla',
  'Angola',
  'Antigua and Barbuda',
  'Bangladesh',
  'Benin',
  'Botswana',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Burkina Faso',
  'Burundi',
  'Vanuatu',
  'Venezuela',
  '"Virgin Islands, U.S."',
  'Gabon',
  'Haiti',
  'Gambia',
  'Ghana',
  'Guinea',
  'Honduras',
  'Grenada',
  'Guam',
  'Djibouti',
  'Zambia',
  'Zimbabwe',
  'Iraq',
  '"Iran, Islamic Republic of"',
  'Yemen',
  'Cambodia',
  'Kyrgyzstan',
  'Kiribati',
  'Cocos (Keeling) Islands',
  'Comoros',
  'Congo',
  '"Congo, Democratic Republic of the"',
  '"Korea, Democratic People\'s republic of"',
  'Costa Rica',
  'Cuba',
  'Lao People\'s Democratic Republic',
  'Lesotho',
  'Lebanon',
  'Holy See (Vatican City State)',
  'Pitcairn',
  'Rwanda',
  'Sao Tome and Principe',
  'Swaziland',
  '"Saint Helena, Ascension And Tristan Da Cunha"',
  'Northern Mariana Islands',
  'Libyan Arab Jamahiriya',
  'Mauritania',
  'Madagascar',
  'Mayotte',
  'Macao',
  'Malawi',
  'Mali',
  'United States Minor Outlying Islands',
  '"Micronesia, Federated States of"',
  'Mozambique',
  'Montserrat',
  'Burma',
  'Namibia',
  'Nauru',
  'Niger',
  'Nigeria',
  'Niue',
  'New Caledonia',
  'Cook Islands',
  'Turks and Caicos Islands',
  'Bouvet Island',
  'Norfolk Island',
  'Christmas Island',
  'Heard Island and McDonald Islands',
  'Pakistan',
  '"Palestinian Territory, Occupied"',
  'Saint Pierre and Miquelon',
  'Syrian Arab Republic',
  'Somalia',
  'Sudan',
  'Sierra Leone',
  'Tajikistan',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Tuvalu',
  'Turkmenistan',
  'Uganda',
  'Wallis and Futuna',
  'French Polynesia',
  'French Southern Territories',
  'Central African Republic',
  'Chad',
  'Svalbard and Jan Mayen',
  'Equatorial Guinea',
  'Eritrea',
  'Ethiopia',
  'South Georgia and the South Sandwich Islands',
  'South Sudan'
]
